AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'config.ru'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/*_helper.rb'
    - 'vendor/**/*'
  NewCops: enable

Style/Documentation:
  Enabled: false # Don't require a class comment
